sudo: false
dist: trusty
language: java
jdk: oraclejdk8
env:
  GOPATH=$TRAVIS_BUILD_DIR/gopath
  VDLPATH=$GOPATH/src
  VANADIUM_CORE_REPO=$GOPATH

before_install:
  - GIMME_OUTPUT=$(gimme 1.11.1) && eval "$GIMME_OUTPUT"
  - mkdir -p $TRAVIS_BUILD_DIR/gopath/src

install:
  - echo "GOPATH:" $GOPATH
  - echo "VDLPATH:" $VDLPATH
  - go get v.io/... 
  - go install v.io/...

script:
  - ls $GOPATH/src
  - ls $GOPATH/src/v.io
  - ls $GOPATH/src/v.io/x/jni/builder
  - ls -R $GOPATH/src/v.io/x
  - ./gradlew clean publishToMavenLocal -i
  - ./gradlew clean test -i
 
notifications:
  email:
    receipients:
      - vanadium-ci@v.io
    on_success: never
    on_failure: always
