sudo: false
dist: trusty
language:  java
jdk: oraclejdk8
env:
  GOPATH=$TRAVIS_BUILD_DIR
  VDLPATH=$GOPATH/src
  VANADIUM_CORE_REPO=$TRAVIS_BUILD_DIR

before_install:
  - GIMME_OUTPUT=$(gimme 1.11.1) && eval "$GIMME_OUTPUT"
  - mkdir $TRAVIS_BUILD_DIR/src

install:
  - echo "GOPATH:" $GOPATH
  - echo "VDLPATH:" $VDLPATH
  - go get v.io/... 
  - go install v.io/...

script:
  - echo "GOPATH:" $GOPATH
  - echo "VDLPATH:" $VDLPATH
  - echo "VANADIUM_CORE_REPO" ${VANADIUM_CORE_REPO}
  - ./gradlew clean publishToMavenLocal -i
  - ./gradlew clean test -i
 
notifications:
  email:
    receipients:
      - vanadium-ci@v.io
    on_success: never
    on_failure: always
