sudo: required
dist: trusty
language:  java
jdk: oraclejdk8
env:
  GOPATH=$TRAVIS_BUILD_DIR
  VDLPATH=$GOPATH/src
  VANADIUM_CORE_REPO=$TRAVIS_BUILD_DIR

pre_install:
  - mkdir $TRAVIS_BUILD_DIR/src

install:
  - echo "GOPATH:" $GOPATH
  - echo "VDLPATH:" $VDLPATH
  - go get -v -t v.io/... 
  - go install v.io/...

script:
  - make java
  - make test-integration
 
notifications:
    email: false
